-- Perfil de cada usuario: imagen (foto subida o avatar del catálogo), texto
-- libre "sobre mí" y si ya completó el editor obligatorio del primer login.
-- nombre/apellidos/mote siguen viviendo en la tabla usuario.
CREATE TABLE perfil (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    BIGINT       NOT NULL REFERENCES usuario (id) ON DELETE CASCADE,
    sobre_mi      VARCHAR(500),
    imagen_tipo   VARCHAR(10)  NOT NULL,
    imagen_ref    VARCHAR(80)  NOT NULL,
    completado    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_perfil_usuario UNIQUE (usuario_id),
    CONSTRAINT ck_perfil_imagen_tipo CHECK (imagen_tipo IN ('FOTO', 'AVATAR'))
);
