-- "A dice que su pareja en la peña es B". pareja_usuario_id se rellena cuando B
-- tiene cuenta. Un usuario solo puede estar en un vínculo VIVO
-- (estado <> 'RECHAZADO') a la vez, sea como solicitante o como pareja: dos
-- índices únicos parciales lo garantizan.
CREATE TABLE vinculo_pareja (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitante_id     BIGINT       NOT NULL REFERENCES usuario (id) ON DELETE CASCADE,
    pareja_usuario_id  BIGINT       REFERENCES usuario (id) ON DELETE SET NULL,
    pareja_nombre      VARCHAR(140) NOT NULL,
    pareja_telefono    VARCHAR(20)  NOT NULL,
    estado             VARCHAR(20)  NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_vinculo_estado CHECK (estado IN ('SIN_CUENTA', 'PENDIENTE', 'ACEPTADO', 'RECHAZADO'))
);

CREATE UNIQUE INDEX uk_vinculo_solicitante_vivo
    ON vinculo_pareja (solicitante_id) WHERE estado <> 'RECHAZADO';
CREATE UNIQUE INDEX uk_vinculo_pareja_usuario_vivo
    ON vinculo_pareja (pareja_usuario_id) WHERE pareja_usuario_id IS NOT NULL AND estado <> 'RECHAZADO';
CREATE INDEX ix_vinculo_pareja_telefono ON vinculo_pareja (pareja_telefono);
