-- Hijos que un miembro declara en su perfil. En la tarjeta del padre/madre solo
-- se muestra el nombre, y solo si visible = true. Si hay vínculo de pareja
-- ACEPTADO, el hijo cuelga de vinculo_pareja_id y lo ven/editan los dos adultos.
-- Si el hijo tiene teléfono y se registra, usuario_id lo enlaza y pasa a tener
-- tarjeta propia.
CREATE TABLE hijo (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creador_id         BIGINT      NOT NULL REFERENCES usuario (id) ON DELETE CASCADE,
    vinculo_pareja_id  BIGINT      REFERENCES vinculo_pareja (id) ON DELETE SET NULL,
    nombre             VARCHAR(80) NOT NULL,
    mayor_de_edad      BOOLEAN     NOT NULL DEFAULT FALSE,
    telefono           VARCHAR(20),
    visible            BOOLEAN     NOT NULL DEFAULT FALSE,
    usuario_id         BIGINT      REFERENCES usuario (id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_hijo_usuario UNIQUE (usuario_id)
);

CREATE INDEX ix_hijo_creador ON hijo (creador_id);
CREATE INDEX ix_hijo_vinculo ON hijo (vinculo_pareja_id);
CREATE INDEX ix_hijo_telefono ON hijo (telefono);
