-- Un evento de la peña (quedada, fiesta...). fecha = día de inicio, y es la que
-- se muestra y por la que se ordena el listado; fecha_fin es opcional (San
-- Miguel dura un fin de semana). creado_por puede ser NULL: los eventos
-- sembrados no tienen creador y solo los gestionan los administradores.
CREATE TABLE evento (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pena_id     BIGINT        NOT NULL REFERENCES pena (id),
    nombre      VARCHAR(120)  NOT NULL,
    descripcion VARCHAR(2000),
    lugar       VARCHAR(160),
    fecha       DATE          NOT NULL,
    fecha_fin   DATE,
    creado_por  BIGINT        REFERENCES usuario (id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_evento_fecha_fin CHECK (fecha_fin IS NULL OR fecha_fin >= fecha)
);

CREATE INDEX ix_evento_pena_fecha ON evento (pena_id, fecha DESC);
