-- Petición de un miembro normal para crear un evento (tipo CREAR: un "crédito"
-- por evento) o para borrar uno que él creó (tipo BORRAR). Un admin la aprueba o
-- la rechaza. Espejo de solicitud_ingreso.
--   CREAR:  evento_id NULL hasta que el crédito se consume al crear el evento.
--   BORRAR: evento_id obligatorio; al aprobar se borra el evento.
CREATE TABLE solicitud_evento (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pena_id        BIGINT       NOT NULL REFERENCES pena (id),
    solicitante_id BIGINT       NOT NULL REFERENCES usuario (id) ON DELETE CASCADE,
    tipo           VARCHAR(8)   NOT NULL,
    evento_id      BIGINT       REFERENCES evento (id) ON DELETE SET NULL,
    mensaje        VARCHAR(500),
    estado         VARCHAR(12)  NOT NULL,
    motivo_rechazo VARCHAR(500),
    resuelta_por   BIGINT       REFERENCES usuario (id),
    resuelta_at    TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_solicitud_evento_tipo   CHECK (tipo IN ('CREAR', 'BORRAR')),
    CONSTRAINT ck_solicitud_evento_estado CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA'))
);

-- Un miembro solo puede tener UNA solicitud CREAR pendiente a la vez.
CREATE UNIQUE INDEX uk_solicitud_evento_crear_pendiente
    ON solicitud_evento (solicitante_id)
    WHERE tipo = 'CREAR' AND estado = 'PENDIENTE';

-- Un evento solo puede tener UNA solicitud BORRAR pendiente a la vez.
CREATE UNIQUE INDEX uk_solicitud_evento_borrar_pendiente
    ON solicitud_evento (evento_id)
    WHERE tipo = 'BORRAR' AND estado = 'PENDIENTE';

CREATE INDEX ix_solicitud_evento_pena_estado ON solicitud_evento (pena_id, estado);
