-- Una cuenta agrupa el dinero (ingresos, gastos y balance) de un evento que se
-- repite: "San Miguel" lleva una sola cuenta aunque el evento se cree cada año,
-- porque lo que sobra de un año sirve para el siguiente. El diseño de los
-- movimientos llega en una tarea posterior; de momento solo el nombre y la
-- descripción. Se pueden crear más por la UI, así que va por BBDD.
CREATE TABLE cuenta (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pena_id     BIGINT        NOT NULL REFERENCES pena (id),
    nombre      VARCHAR(120)  NOT NULL,
    descripcion VARCHAR(2000),
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_cuenta_pena_nombre UNIQUE (pena_id, nombre)
);

CREATE INDEX ix_cuenta_pena ON cuenta (pena_id);
