-- Respuesta de una persona a un evento (Me apunto / No voy / En duda). usuario_id
-- NULL = persona sin app (invitado o añadida a mano por un admin/organizador);
-- en ese caso nombre es obligatorio (lo valida el servicio). registrado_por = el
-- admin/organizador que creó la fila; NULL si respondió la propia persona.
CREATE TABLE asistencia_evento (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id         BIGINT       NOT NULL REFERENCES evento (id) ON DELETE CASCADE,
    usuario_id        BIGINT       REFERENCES usuario (id) ON DELETE CASCADE,
    nombre            VARCHAR(120),
    estado            VARCHAR(16)  NOT NULL,
    registrado_por_id BIGINT       REFERENCES usuario (id) ON DELETE SET NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_asistencia_estado CHECK (estado IN ('APUNTADO', 'NO_VOY', 'EN_DUDA'))
);

-- Una persona con app solo tiene una respuesta por evento; las añadidas a mano
-- (usuario_id NULL) no chocan entre sí.
CREATE UNIQUE INDEX uq_asistencia_evento_usuario
    ON asistencia_evento (evento_id, usuario_id) WHERE usuario_id IS NOT NULL;
CREATE INDEX ix_asistencia_evento ON asistencia_evento (evento_id);
