-- Cada vez que un admin u organizador pulsa "Mandar notificación" se guarda una
-- fila. Sirve para la regla de reenvío (>= 48 h desde el último envío) y para la
-- pantalla bloqueante (hay notificación + no he respondido).
CREATE TABLE notificacion_evento (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id      BIGINT      NOT NULL REFERENCES evento (id) ON DELETE CASCADE,
    texto          VARCHAR(500),
    enviada_por_id BIGINT      NOT NULL REFERENCES usuario (id),
    enviada_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_notificacion_evento ON notificacion_evento (evento_id, enviada_at DESC);
