-- Catálogo de bebidas para la ficha de San Miguel. "Otra…" en la ficha crea una
-- fila PENDIENTE; un admin la acepta (sale en los desplegables) o la rechaza.
CREATE TABLE bebida (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo             VARCHAR(16)  NOT NULL,
    nombre           VARCHAR(80)  NOT NULL,
    estado           VARCHAR(16)  NOT NULL DEFAULT 'PENDIENTE',
    propuesta_por_id BIGINT       REFERENCES usuario (id) ON DELETE SET NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_bebida_tipo   CHECK (tipo IN ('ALCOHOL', 'REFRESCO')),
    CONSTRAINT ck_bebida_estado CHECK (estado IN ('ACEPTADA', 'PENDIENTE', 'RECHAZADA'))
);
CREATE UNIQUE INDEX uq_bebida_tipo_nombre ON bebida (tipo, lower(nombre));

INSERT INTO bebida (tipo, nombre, estado) VALUES
  ('ALCOHOL','Barceló','ACEPTADA'), ('ALCOHOL','White Label','ACEPTADA'),
  ('ALCOHOL','Brugal','ACEPTADA'), ('ALCOHOL','JB','ACEPTADA'),
  ('ALCOHOL','Legendario','ACEPTADA'), ('ALCOHOL','Puerto de Indias','ACEPTADA'),
  ('ALCOHOL','Four Roses','ACEPTADA'), ('ALCOHOL','Negruita','ACEPTADA'),
  ('ALCOHOL','Red Label','ACEPTADA'), ('ALCOHOL','Beefeater','ACEPTADA'),
  ('ALCOHOL','Malibú','ACEPTADA'), ('ALCOHOL','Tanqueray','ACEPTADA'),
  ('ALCOHOL','Negrita','ACEPTADA'), ('ALCOHOL','Ballantines','ACEPTADA'),
  ('ALCOHOL','Absolut','ACEPTADA'), ('ALCOHOL','Seagram''s','ACEPTADA'),
  ('ALCOHOL','DYC','ACEPTADA'), ('ALCOHOL','Larios','ACEPTADA'),
  ('REFRESCO','Coca-Cola','ACEPTADA'), ('REFRESCO','Coca-Cola Zero','ACEPTADA'),
  ('REFRESCO','Coca-Cola Light','ACEPTADA'), ('REFRESCO','Fanta Naranja','ACEPTADA'),
  ('REFRESCO','Fanta Limón','ACEPTADA'), ('REFRESCO','Schweppes Limón','ACEPTADA'),
  ('REFRESCO','Sprite','ACEPTADA'), ('REFRESCO','Sprite Zero','ACEPTADA'),
  ('REFRESCO','Nestea','ACEPTADA'), ('REFRESCO','Tónica','ACEPTADA'),
  ('REFRESCO','Trina Naranja','ACEPTADA'), ('REFRESCO','Aquarius','ACEPTADA');

ALTER TABLE cuenta ADD COLUMN lleva_ficha_bebida BOOLEAN NOT NULL DEFAULT false;
UPDATE cuenta SET lleva_ficha_bebida = true
 WHERE nombre = 'San Miguel'
   AND pena_id = (SELECT id FROM pena WHERE slug = 'baniterio');
