-- Declaración de pago (pieza 5, parcial). Un peñista (o un admin, para sí mismo)
-- dice desde el detalle del evento que ha pagado su cuota; queda PENDIENTE hasta
-- que un administrador la confirma (marca las fichas cubiertas como pagadas) o la
-- rechaza. El atajo del admin en el modal "Listado de asistentes" sigue marcando
-- fichas directamente sin pasar por aquí.
CREATE TABLE pago_declarado (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id     BIGINT      NOT NULL REFERENCES evento (id) ON DELETE CASCADE,
    declarado_por BIGINT      NOT NULL REFERENCES usuario (id) ON DELETE CASCADE,
    importe       NUMERIC(7,2) NOT NULL,
    metodo_pago   VARCHAR(16) NOT NULL,
    estado        VARCHAR(16) NOT NULL,
    resuelto_por  BIGINT      REFERENCES usuario (id) ON DELETE SET NULL,
    resuelto_at   TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_pago_declarado_metodo CHECK (metodo_pago IN ('BIZUM', 'TRANSFERENCIA', 'EFECTIVO')),
    CONSTRAINT ck_pago_declarado_estado CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'RECHAZADA'))
);

-- Qué asistencias cubre este pago (siempre la del propio declarante, más
-- pareja/hijos/invitados que haya marcado).
CREATE TABLE pago_declarado_cubre (
    pago_declarado_id BIGINT NOT NULL REFERENCES pago_declarado (id) ON DELETE CASCADE,
    asistencia_id     BIGINT NOT NULL REFERENCES asistencia_evento (id) ON DELETE CASCADE,
    PRIMARY KEY (pago_declarado_id, asistencia_id)
);

-- Como mucho una declaración sin resolver por (evento, declarante).
CREATE UNIQUE INDEX ux_pago_declarado_pendiente
    ON pago_declarado (evento_id, declarado_por) WHERE estado = 'PENDIENTE';
CREATE INDEX ix_pago_declarado_estado ON pago_declarado (estado, created_at);
