-- Libro de movimientos por cuenta (estilo Excel del tesorero): la primera fila
-- es el saldo inicial, y cada cuota que llega a la cuenta de la peña añade una
-- fila. Los gastos, más adelante, serán filas negativas.
CREATE TABLE movimiento_cuenta (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id           BIGINT       NOT NULL REFERENCES cuenta (id) ON DELETE CASCADE,
    concepto            VARCHAR(200) NOT NULL,
    importe             NUMERIC(9,2) NOT NULL,
    fecha               DATE         NOT NULL DEFAULT current_date,
    origen              VARCHAR(16)  NOT NULL,
    ficha_asistencia_id BIGINT       REFERENCES ficha_bebida (asistencia_id) ON DELETE SET NULL,
    creado_por          BIGINT       REFERENCES usuario (id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_movimiento_origen CHECK (origen IN ('SALDO_INICIAL', 'CUOTA', 'AJUSTE'))
);

CREATE INDEX ix_movimiento_cuenta ON movimiento_cuenta (cuenta_id, fecha, id);
CREATE UNIQUE INDEX ux_movimiento_ficha
    ON movimiento_cuenta (ficha_asistencia_id) WHERE ficha_asistencia_id IS NOT NULL;

-- Saldo inicial de San Miguel: lo que sobró del año anterior.
INSERT INTO movimiento_cuenta (cuenta_id, concepto, importe, fecha, origen)
SELECT c.id, 'Saldo del año anterior', 91.13, DATE '2026-01-01', 'SALDO_INICIAL'
FROM cuenta c
JOIN pena p ON p.id = c.pena_id
WHERE p.slug = 'baniterio' AND c.nombre = 'San Miguel'
  AND NOT EXISTS (
      SELECT 1 FROM movimiento_cuenta m
      WHERE m.cuenta_id = c.id AND m.origen = 'SALDO_INICIAL'
  );

-- Estado de pago de la cuota: cuatro niveles en vez del booleano `pagado`.
ALTER TABLE ficha_bebida ADD COLUMN estado_pago VARCHAR(28) NOT NULL DEFAULT 'PENDIENTE_PAGO';
UPDATE ficha_bebida
   SET estado_pago = CASE WHEN pagado THEN 'CONFIRMADO_EN_CUENTA' ELSE 'PENDIENTE_PAGO' END;
ALTER TABLE ficha_bebida DROP COLUMN pagado;
ALTER TABLE ficha_bebida ADD CONSTRAINT ck_ficha_estado_pago
    CHECK (estado_pago IN ('PENDIENTE_PAGO', 'DECLARADO',
                           'CONFIRMADO_PENDIENTE_ENVIO', 'CONFIRMADO_EN_CUENTA'));
