-- Migración Flyway nº 2: crea la tabla de usuarios. password_hash guarda el
-- hash BCrypt, nunca la contraseña en claro. es_superadmin / activo son flags.
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(160) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nombre VARCHAR(80) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    mote VARCHAR(60),
    es_superadmin BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_usuario_telefono UNIQUE (telefono),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);
