-- Inventario de la peña: material y bebida que hay almacenado, agrupado en cinco
-- categorías. Una fila por combinación nombre + tamaño. La cantidad admite
-- decimales (1.5 botellas). El "tamaño" se valida en el servicio contra la lista
-- fija de cada categoría (CategoriaInventario). Siembra idempotente por
-- (pena_id, categoria, nombre, tamano) vía INSERT ... WHERE NOT EXISTS.
CREATE TABLE articulo_inventario (
    id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pena_id   BIGINT        NOT NULL REFERENCES pena (id),
    categoria VARCHAR(20)   NOT NULL,
    nombre    VARCHAR(120)  NOT NULL,
    tamano    VARCHAR(20)   NOT NULL,
    cantidad  NUMERIC(8, 2) NOT NULL DEFAULT 0,
    orden     INT           NOT NULL DEFAULT 0,
    CONSTRAINT ck_articulo_inventario_categoria
        CHECK (categoria IN ('ALCOHOL', 'CERVEZA', 'REFRESCOS', 'LIMPIEZA', 'COMIDA')),
    CONSTRAINT ck_articulo_inventario_cantidad CHECK (cantidad >= 0)
);
CREATE INDEX ix_articulo_inventario_pena ON articulo_inventario (pena_id);

INSERT INTO articulo_inventario (pena_id, categoria, nombre, tamano, cantidad, orden)
SELECT p.id, v.categoria, v.nombre, v.tamano, v.cantidad, v.orden
FROM pena p
CROSS JOIN (VALUES
    ('ALCOHOL',   'Tanqueray',            '70 cl',   1.5,  1),
    ('ALCOHOL',   'Seagram''s',           '70 cl',   0.8,  2),
    ('ALCOHOL',   'Beefeater',            '1 L',     0.8,  3),
    ('ALCOHOL',   'Negrita',              '1 L',     1,    4),
    ('ALCOHOL',   'Legendario',           '70 cl',   2.5,  5),
    ('ALCOHOL',   'Puerto de Indias',     '1 L',     0.8,  6),
    ('ALCOHOL',   'Barceló',              '70 cl',   0.5,  7),
    ('ALCOHOL',   'Brugal',               '1 L',     1,    8),
    ('ALCOHOL',   'Four Roses',           '70 cl',   0.8,  9),
    ('ALCOHOL',   'Four Roses',           '1 L',     1,    10),
    ('ALCOHOL',   'Ballantine''s',        '70 cl',   1,    11),
    ('CERVEZA',   'Sin gluten',           'lata',    8,    1),
    ('CERVEZA',   'Mahou Clásica',        'lata',    192,  2),
    ('CERVEZA',   'Mahou 0,0 Tostada',    'lata',    14,   3),
    ('CERVEZA',   'Mixta',                'lata',    3,    4),
    ('CERVEZA',   'Coronita',             'lata',    3,    5),
    ('LIMPIEZA',  'Bayetas',              'unidad',  5,    1),
    ('LIMPIEZA',  'Fregasuelos',          'litro',   0.5,  2),
    ('LIMPIEZA',  'Papel de cocina',      'rollo',   1.5,  3),
    ('LIMPIEZA',  'Platos',               'unidad',  35,   4),
    ('LIMPIEZA',  'Vasos de chupito',     'unidad',  25,   5),
    ('LIMPIEZA',  'Papel higiénico',      'rollo',   12,   6),
    ('LIMPIEZA',  'Vasos de mini',        'unidad',  100,  7),
    ('LIMPIEZA',  'Vasos de sidra',       'unidad',  35,   8),
    ('LIMPIEZA',  'Mantel 1,2 x 5',       'unidad',  1,    9),
    ('REFRESCOS', 'Tónica',               'botella', 3,    1),
    ('REFRESCOS', 'Coca-Cola Zero',       'botella', 15,   2),
    ('REFRESCOS', 'Coca-Cola Zero Zero',  'botella', 5,    3),
    ('REFRESCOS', 'Red Bull',             'lata',    2,    4),
    ('REFRESCOS', 'Gin-tonic Tanqueray',  'lata',    2,    5),
    ('REFRESCOS', 'Aquarius naranja',     'botella', 4,    6),
    ('REFRESCOS', 'Aquarius limón',       'botella', 1,    7),
    ('REFRESCOS', 'Agua',                 'garrafa', 3,    8),
    ('REFRESCOS', 'Coca-Cola Light',      'botella', 5,    9),
    ('REFRESCOS', 'Coca-Cola normal',     'botella', 4,    10),
    ('REFRESCOS', 'Nestea',               'botella', 4,    11),
    ('REFRESCOS', 'Fanta limón',          'botella', 1,    12),
    ('REFRESCOS', 'Tinto de verano',      'botella', 4,    13)
) AS v(categoria, nombre, tamano, cantidad, orden)
WHERE p.slug = 'baniterio'
  AND NOT EXISTS (
      SELECT 1 FROM articulo_inventario a
      WHERE a.pena_id = p.id AND a.categoria = v.categoria
        AND a.nombre = v.nombre AND a.tamano = v.tamano
  );
