-- Inventario de la fiesta: material y bebida del inventario general que se ha
-- "enviado" a un evento concreto. Una fila por (evento, artículo de origen);
-- reenviar el mismo artículo suma en la fila existente (UNIQUE). categoria /
-- nombre / tamano son copia congelada del momento del envío. Al "devolver", la
-- cantidad vuelve a articulo_inventario.<articulo_inventario_id> y la fila se
-- borra. Sin siembra.
CREATE TABLE articulo_evento (
    id                     BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id              BIGINT        NOT NULL REFERENCES evento (id) ON DELETE CASCADE,
    articulo_inventario_id BIGINT        NOT NULL REFERENCES articulo_inventario (id),
    categoria              VARCHAR(20)   NOT NULL,
    nombre                 VARCHAR(120)  NOT NULL,
    tamano                 VARCHAR(20)   NOT NULL,
    cantidad               NUMERIC(8, 2) NOT NULL DEFAULT 0,
    orden                  INT           NOT NULL DEFAULT 0,
    CONSTRAINT ck_articulo_evento_categoria
        CHECK (categoria IN ('ALCOHOL', 'CERVEZA', 'REFRESCOS', 'LIMPIEZA', 'COMIDA')),
    CONSTRAINT ck_articulo_evento_cantidad CHECK (cantidad >= 0),
    CONSTRAINT uq_articulo_evento UNIQUE (evento_id, articulo_inventario_id)
);
CREATE INDEX ix_articulo_evento_evento ON articulo_evento (evento_id);
