-- Lista de la compra por evento. `regla_compra` es la plantilla global de la
-- peña (una fila por artículo, con su fórmula tipada). `regla_compra_evento` son
-- las instancias por evento: se copian de la plantilla la primera vez que se
-- abre la lista de un evento y a partir de ahí se editan solo en ese evento.
-- El descuento del inventario de la fiesta (bloque 2) NO está aquí.
CREATE TABLE regla_compra (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pena_id      BIGINT        NOT NULL REFERENCES pena (id),
    categoria    VARCHAR(20)   NOT NULL,
    nombre       VARCHAR(120)  NOT NULL,
    tamano       VARCHAR(20)   NOT NULL,
    tipo_formula VARCHAR(30)   NOT NULL,
    factor       NUMERIC(8, 3) NOT NULL,
    por_cada     INT,
    orden        INT           NOT NULL DEFAULT 0,
    CONSTRAINT ck_regla_compra_categoria
        CHECK (categoria IN ('ALCOHOL', 'CERVEZA', 'REFRESCOS', 'LIMPIEZA', 'COMIDA')),
    CONSTRAINT ck_regla_compra_tipo CHECK (tipo_formula IN (
        'POR_PENISTA', 'POR_PENISTA_DIA', 'POR_DIA', 'POR_EVENTO', 'POR_CADA_N_PENISTAS',
        'CERVEZA_ALTERNATIVA', 'TINTO_ALTERNATIVA', 'ALCOHOL_SELECCIONADO', 'REFRESCO_SELECCIONADO')),
    CONSTRAINT ck_regla_compra_factor CHECK (factor >= 0),
    CONSTRAINT ck_regla_compra_por_cada CHECK (por_cada IS NULL OR por_cada > 0),
    CONSTRAINT uq_regla_compra UNIQUE (pena_id, categoria, nombre, tipo_formula)
);

CREATE TABLE regla_compra_evento (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id         BIGINT        NOT NULL REFERENCES evento (id) ON DELETE CASCADE,
    categoria         VARCHAR(20)   NOT NULL,
    nombre            VARCHAR(120)  NOT NULL,
    tamano            VARCHAR(20)   NOT NULL,
    tipo_formula      VARCHAR(30)   NOT NULL,
    factor            NUMERIC(8, 3) NOT NULL,
    por_cada          INT,
    orden             INT           NOT NULL DEFAULT 0,
    origen            VARCHAR(10)   NOT NULL,
    cantidad_ajustada NUMERIC(8, 2),
    activa            BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_regla_compra_evento_categoria
        CHECK (categoria IN ('ALCOHOL', 'CERVEZA', 'REFRESCOS', 'LIMPIEZA', 'COMIDA')),
    CONSTRAINT ck_regla_compra_evento_tipo CHECK (tipo_formula IN (
        'POR_PENISTA', 'POR_PENISTA_DIA', 'POR_DIA', 'POR_EVENTO', 'POR_CADA_N_PENISTAS',
        'CERVEZA_ALTERNATIVA', 'TINTO_ALTERNATIVA', 'ALCOHOL_SELECCIONADO', 'REFRESCO_SELECCIONADO')),
    CONSTRAINT ck_regla_compra_evento_origen CHECK (origen IN ('PLANTILLA', 'MANUAL')),
    CONSTRAINT ck_regla_compra_evento_factor CHECK (factor >= 0),
    CONSTRAINT ck_regla_compra_evento_por_cada CHECK (por_cada IS NULL OR por_cada > 0),
    CONSTRAINT ck_regla_compra_evento_ajustada CHECK (cantidad_ajustada IS NULL OR cantidad_ajustada >= 0),
    CONSTRAINT uq_regla_compra_evento UNIQUE (evento_id, categoria, nombre, tipo_formula)
);
CREATE INDEX ix_regla_compra_evento_evento ON regla_compra_evento (evento_id);

-- Siembra de la plantilla con las fórmulas actuales de la peña. Idempotente por
-- (pena_id, categoria, nombre, tipo_formula).
INSERT INTO regla_compra (pena_id, categoria, nombre, tamano, tipo_formula, factor, por_cada, orden)
SELECT p.id, v.categoria, v.nombre, v.tamano, v.tipo_formula, v.factor, v.por_cada, v.orden
FROM pena p
CROSS JOIN (VALUES
    ('ALCOHOL',   '',                            '70 cl',   'ALCOHOL_SELECCIONADO',  0.5, NULL, 1),
    ('CERVEZA',   'Cerveza',                     'lata',    'CERVEZA_ALTERNATIVA',   5,   NULL, 1),
    ('REFRESCOS', '',                            'botella', 'REFRESCO_SELECCIONADO', 1,   NULL, 1),
    ('REFRESCOS', 'Tinto de verano',             'botella', 'TINTO_ALTERNATIVA',     1,   NULL, 2),
    ('REFRESCOS', 'Hielos',                      'bolsa',   'POR_PENISTA',           1,   NULL, 3),
    ('LIMPIEZA',  'Bayetas',                     'unidad',  'POR_CADA_N_PENISTAS',   2,   30,   1),
    ('LIMPIEZA',  'Fregasuelos',                 'litro',   'POR_CADA_N_PENISTAS',   0.2, 50,   2),
    ('LIMPIEZA',  'Papel de cocina',             'rollo',   'POR_DIA',               1,   NULL, 3),
    ('LIMPIEZA',  'Platos',                      'unidad',  'POR_PENISTA',           3,   NULL, 4),
    ('LIMPIEZA',  'Vasos de chupito',            'unidad',  'POR_PENISTA',           3,   NULL, 5),
    ('LIMPIEZA',  'Papel higiénico',             'rollo',   'POR_CADA_N_PENISTAS',   6,   30,   6),
    ('LIMPIEZA',  'Vasos de mini',               'unidad',  'POR_PENISTA_DIA',       3,   NULL, 7),
    ('LIMPIEZA',  'Vasos de sidra',              'unidad',  'POR_PENISTA_DIA',       3,   NULL, 8),
    ('LIMPIEZA',  'Mantel',                      'unidad',  'POR_DIA',               1,   NULL, 9),
    ('LIMPIEZA',  'Vasos de invitar',            'unidad',  'POR_EVENTO',            50,  NULL, 10),
    ('LIMPIEZA',  'Film transparente',           'rollo',   'POR_EVENTO',            1,   NULL, 11),
    ('COMIDA',    'Paletilla ibérica',           'unidad',  'POR_EVENTO',            1,   NULL, 1),
    ('COMIDA',    'Salchichón ibérico',          'unidad',  'POR_EVENTO',            1,   NULL, 2),
    ('COMIDA',    'Chorizo ibérico',             'unidad',  'POR_EVENTO',            1,   NULL, 3),
    ('COMIDA',    'Nocilla grande',              'bote',    'POR_CADA_N_PENISTAS',   1,   12,   4),
    ('COMIDA',    'Nocilla pequeña sin gluten',  'bote',    'POR_EVENTO',            1,   NULL, 5),
    ('COMIDA',    'Pan de molde sin gluten',     'paquete', 'POR_EVENTO',            1,   NULL, 6),
    ('COMIDA',    'Picos',                       'paquete', 'POR_CADA_N_PENISTAS',   2,   10,   7),
    ('COMIDA',    'Pan de molde',                'paquete', 'POR_CADA_N_PENISTAS',   2,   12,   8)
) AS v(categoria, nombre, tamano, tipo_formula, factor, por_cada, orden)
WHERE p.slug = 'baniterio'
  AND NOT EXISTS (
      SELECT 1 FROM regla_compra r
      WHERE r.pena_id = p.id AND r.categoria = v.categoria
        AND r.nombre = v.nombre AND r.tipo_formula = v.tipo_formula
  );
