-- Lista de la compra, bloque 1.5: "comprado" + bloqueo.
--  * evento.lista_compra_bloqueada: al activarlo, la lista deja de recalcularse
--    al apuntarse gente; el admin sigue pudiendo ajustar reglas a mano.
--  * articulo_evento.cantidad_comprada: parte de la fila que se compró desde la
--    lista (sin artículo de origen). articulo_inventario_id pasa a nullable y la
--    clave de fusión pasa a (evento, categoria, nombre, tamano) para que stock y
--    comprado del mismo producto caigan en la misma fila.
--  * linea_compra_evento: la lista mostrada, materializada. Se sincroniza con el
--    cálculo en cada lectura mientras no esté bloqueada; las líneas compradas
--    quedan congeladas.
ALTER TABLE evento ADD COLUMN lista_compra_bloqueada BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE articulo_evento ALTER COLUMN articulo_inventario_id DROP NOT NULL;
ALTER TABLE articulo_evento ADD COLUMN cantidad_comprada NUMERIC(8, 2) NOT NULL DEFAULT 0;
ALTER TABLE articulo_evento ADD CONSTRAINT ck_articulo_evento_comprada CHECK (cantidad_comprada >= 0);
ALTER TABLE articulo_evento DROP CONSTRAINT uq_articulo_evento;
ALTER TABLE articulo_evento ADD CONSTRAINT uq_articulo_evento_producto
    UNIQUE (evento_id, categoria, nombre, tamano);

CREATE TABLE linea_compra_evento (
    id                 BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id          BIGINT        NOT NULL REFERENCES evento (id) ON DELETE CASCADE,
    categoria          VARCHAR(20)   NOT NULL,
    nombre             VARCHAR(120)  NOT NULL,
    tamano             VARCHAR(20)   NOT NULL,
    cantidad           NUMERIC(8, 2) NOT NULL,
    orden              INT           NOT NULL DEFAULT 0,
    dinamica           BOOLEAN       NOT NULL DEFAULT FALSE,
    necesita_ficha     BOOLEAN       NOT NULL DEFAULT FALSE,
    ajustada           BOOLEAN       NOT NULL DEFAULT FALSE,
    comprada           BOOLEAN       NOT NULL DEFAULT FALSE,
    articulo_evento_id BIGINT        REFERENCES articulo_evento (id) ON DELETE SET NULL,
    CONSTRAINT ck_lce_categoria
        CHECK (categoria IN ('ALCOHOL', 'CERVEZA', 'REFRESCOS', 'LIMPIEZA', 'COMIDA')),
    CONSTRAINT ck_lce_cantidad CHECK (cantidad >= 0),
    CONSTRAINT uq_lce UNIQUE (evento_id, categoria, nombre, tamano)
);
CREATE INDEX ix_lce_evento ON linea_compra_evento (evento_id);
