-- Migración Flyway nº 3: la "lista blanca" de teléfonos con permiso para
-- registrarse en una peña. FK pena_id → pena. usado = ya se registró alguien.
CREATE TABLE telefono_autorizado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefono VARCHAR(20) NOT NULL,
    pena_id BIGINT NOT NULL REFERENCES pena (id),
    usado BOOLEAN NOT NULL DEFAULT FALSE,
    autorizado_por BIGINT REFERENCES usuario (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_telefono_autorizado_telefono UNIQUE (telefono)
);

CREATE INDEX ix_telefono_autorizado_pena ON telefono_autorizado (pena_id);
