CREATE TABLE membresia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario (id),
    pena_id BIGINT NOT NULL REFERENCES pena (id),
    rol VARCHAR(20) NOT NULL,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_membresia_usuario_pena UNIQUE (usuario_id, pena_id),
    CONSTRAINT ck_membresia_rol CHECK (rol IN ('ADMIN', 'MIEMBRO'))
);

CREATE INDEX ix_membresia_pena ON membresia (pena_id);
CREATE INDEX ix_membresia_usuario ON membresia (usuario_id);
