-- Precio bebidas (alcohol): catálogo de tiendas de la peña, pestañas de
-- tamaño por evento y el precio de cada marca en cada tienda para ese
-- tamaño. Solo se guarda fila en precio_bebida_evento cuando hay un precio
-- metido; vaciar una celda borra la fila. Ver spec
-- docs/superpowers/specs/2026-09-17-precio-bebidas-alcohol-design.md.

CREATE TABLE tienda (
    id      BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pena_id BIGINT      NOT NULL REFERENCES pena (id),
    nombre  VARCHAR(80) NOT NULL,
    orden   INT         NOT NULL DEFAULT 0,
    CONSTRAINT uq_tienda_pena_nombre UNIQUE (pena_id, nombre)
);
CREATE INDEX ix_tienda_pena ON tienda (pena_id);

INSERT INTO tienda (pena_id, nombre, orden)
SELECT p.id, v.nombre, v.orden
FROM pena p
CROSS JOIN (VALUES
    ('Alcampo', 1), ('Makro', 2), ('Carrefour', 3), ('Mercadona', 4),
    ('Hipercor', 5), ('Amazon', 6), ('Merkocash', 7)
) AS v(nombre, orden);

-- Pestañas de tamaño de un evento (compartidas por todas las marcas); sin
-- siembra, se materializan con "70 cl" y "1 L" al abrir la rejilla por
-- primera vez.
CREATE TABLE tamano_precio_bebida_evento (
    id        BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT      NOT NULL REFERENCES evento (id) ON DELETE CASCADE,
    tamano    VARCHAR(20) NOT NULL,
    orden     INT         NOT NULL DEFAULT 0,
    CONSTRAINT uq_tamano_precio_bebida_evento UNIQUE (evento_id, tamano)
);
CREATE INDEX ix_tamano_precio_bebida_evento_evento ON tamano_precio_bebida_evento (evento_id);

CREATE TABLE precio_bebida_evento (
    id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT        NOT NULL REFERENCES evento (id) ON DELETE CASCADE,
    bebida_id BIGINT        NOT NULL REFERENCES bebida (id),
    tamano    VARCHAR(20)   NOT NULL,
    tienda_id BIGINT        NOT NULL REFERENCES tienda (id) ON DELETE CASCADE,
    precio    NUMERIC(8, 2) NOT NULL,
    CONSTRAINT ck_precio_bebida_evento_precio CHECK (precio >= 0),
    CONSTRAINT uq_precio_bebida_evento UNIQUE (evento_id, bebida_id, tamano, tienda_id)
);
CREATE INDEX ix_precio_bebida_evento_evento ON precio_bebida_evento (evento_id);
