-- Áreas del panel a las que se puede conceder acceso a un usuario concreto.
-- Un admin/superadmin las tiene todas de forma implícita (no aparecen aquí).
CREATE TABLE permiso_area (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    BIGINT      NOT NULL REFERENCES usuario (id) ON DELETE CASCADE,
    area          VARCHAR(40) NOT NULL,
    concedido_por BIGINT      REFERENCES usuario (id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_permiso_area UNIQUE (usuario_id, area)
);

-- Hash BCrypt de la contraseña que el solicitante puso al intentar registrarse.
-- Puede faltar (llegó directo a "solicitar acceso" o refrescó la página).
ALTER TABLE solicitud_ingreso ADD COLUMN password_hash VARCHAR(72);
