package com.baniterio.api.identidad;

import java.time.Instant;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entidad JPA = una fila de la tabla {@code usuario}. Cada campo es una columna.
 *
 * <p>Anotaciones:
 * <ul>
 *   <li>{@code @Entity} / {@code @Table} — mapea la clase a la tabla.
 *   <li>{@code @Id} + {@code @GeneratedValue(IDENTITY)} — la PK la genera
 *       Postgres (columna {@code BIGINT GENERATED BY DEFAULT AS IDENTITY}).
 *   <li>{@code @Column} — ajusta nombre/longitud/nulabilidad (debe cuadrar con
 *       lo que crea la migración V2, porque {@code ddl-auto: validate} lo
 *       comprueba al arrancar).
 *   <li>{@code @CreationTimestamp} / {@code @UpdateTimestamp} — Hibernate rellena
 *       las fechas solo.
 *   <li>Lombok ({@code @Getter}, {@code @Builder}, ...) — genera getters,
 *       setters, constructores y el patrón builder sin escribirlos.
 * </ul>
 *
 * <p>{@code passwordHash} guarda el hash BCrypt, nunca la contraseña en claro.
 * Las demás entidades de este paquete siguen este mismo patrón.
 */
@Entity
@Table(name = "usuario")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Usuario {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 20, unique = true)
    private String telefono;

    @Column(nullable = false, length = 160, unique = true)
    private String email;

    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    @Column(nullable = false, length = 80)
    private String nombre;

    @Column(nullable = false, length = 120)
    private String apellidos;

    @Column(length = 60)
    private String mote;

    @Column(name = "es_superadmin", nullable = false)
    private boolean esSuperadmin;

    @Column(nullable = false)
    private boolean activo;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;
}
